### ISSUE TITLE
 Nuxt is not a constructor

### ISSUE THREAD

**Issue by hskww** [nuxt/nuxt-todomvc#3]
Nuxt is not a constructor
server.js

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/todomvc/issues/c9">#c9</a>)</em></sub></div>

**Comment by alterhu2020** [comment]
any update for this issue ,i meet the same error as @hskww  mentioned above.
what I had done is just run the command ` npm run dev` after run the `npm install `
the output from command is as following:
```
D:\todomvc-master>npm run dev

> todomvc@1.0.0 dev D:\todomvc-master
> node server.js

D:\todomvc-master\server.js:26
const nuxt = new Nuxt(config)
             ^
TypeError: Nuxt is not a constructor
    at Object.<anonymous> (D:\todomvc-master\server.js:26:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! todomvc@1.0.0 dev: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the todomvc@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     F:\node_caches\_logs\2017-08-03T14_29_55_869Z-debug.log

D:\todomvc-master>

```

**Comment by fengjiel** [comment]
版本原因、https://github.com/fengjiel/todomvc/tree/Upgraded-version  我之前写的可以参考下 @alterhu2020  @hskww

**Comment by alterhu2020** [comment]
thanks @fengjiel , I had also found caused by the version after upgrading to the latest version.

**Comment by southnan0** [comment]
use yarn instead

**Comment by meizijiu** [comment]
可以说明一下具体原因么，您提供的链接失效了@fengjiel

**Comment by fengjiel** [comment]
建议把server.js 和vuex内的关键代码拷贝下放到最新的项目里  nuxtjs版本更新后一些方法不适用了 @meizijiu

**Comment by meizijiu** [comment]
是的， nuxt的issue里也有类似的提问， https://github.com/nuxt/nuxt.js/issues/1219

**Comment by valeriosillari** [comment]
I try to check the repo and I got this issue. any updates? :)
