### ISSUE TITLE
Nothing but failure =(

### ISSUE THREAD

**Issue by trusktr** [nuxt/nuxt-todomvc#6]
<img width="945" alt="screen shot 2017-09-08 at 10 25 20 pm" src="https://user-images.githubusercontent.com/297678/30237330-a7d2ae42-94e4-11e7-971b-950ef4258946.png">

Repro:

```
yarn install
npm run dev
```

then visit `localhost:3000`

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/todomvc/issues/c11">#c11</a>)</em></sub></div>

**Comment by trusktr** [comment]
I'm on Node 8.1.2

**Comment by highsea** [comment]
Change `todos.length` to `todos&&todos.length`

**Comment by default-writer** [comment]
For windows builds, replace:

```
import TodoHeader from '~components/header'
import TodoFooter from '~components/footer'
```

to

```
import TodoHeader from '~/components/header'
import TodoFooter from '~/components/footer'

```
